version: "3"

services:
  mirotalkwebrtc:
    image: elestio/mirotalk:${SOFTWARE_VERSION_TAG}
    restart: always
    hostname: mirotalkwebrtc
    volumes:
      - .env:/src/.env:ro
      - ./config.js:/src/backend.js/config.js:ro
      # - ./backend/:/src/backend/:ro
      # - ./frontend/:/src/frontend/:ro
    ports:
      - "172.17.0.1:26645:${SERVER_PORT}"
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "172.17.0.1:${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - "./.mongodb_data:/data/db"
    command: mongod --quiet --logpath /dev/null
